# Generated by Django 4.1.7 on 2023-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_recipes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
