# Generated by Django 4.1.7 on 2023-04-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_recipes_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='servings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
