# Generated by Django 4.1.7 on 2023-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_recipes_url_alter_recipes_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
